name: Deploy Docusaurus Docs

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 6 * * 1"

jobs:
  deploy:
    permissions:
      pages: write      
      id-token: write   
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodule: 'recursive'
      - name: Sync docs
        run: |
          git submodule update --init --recursive
          cp -rp RSSHub/website/* .
          name=docusaurus.config.ts
          cp ${name} bak1-${name}
          sed -E "s/url: '.+',/url: 'https:\/\/hantang.github.io',/" < bak1-${name} > bak2-${name}
          sed -E "s/baseUrl: .+,/baseUrl: '\/wayback-rsshub-doc\/',/" < bak2-${name} > bak1-${name}
          mv bak1-${name} ${name}

      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies (pnpm)
        run: pnpm install
      - name: Build Site
        run: pnpm run build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4